language: node_js
node_js:
- 5.2.0
before_install:
- npm install
script:
- webpack
sudo: false
before_deploy:
- npm-prepublish --verbose
deploy:
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
env:
  global:
  # NPM_EMAIL
  - secure: "eMav/QmNoiej+Us39fx1uGF9e1/JuUTtWRBpTPe6iEZDBRsxlSbrnPeHRnzltzyQKoSCTiW8qYtvQOEluR7MX+PTkf0g6R+cZr9J4rIIdH8mDaigpQJId/5SDptqFP31RaYDV+qARWTgpwqYmv5dywxwNoOSUg6pLTto0F0pvMCMYwqmiwfzSqvOmG/BAiZC46+QLEv8Dkw736Uvfxvg0CKQv/d6vMZj9LgoopiZAl135EnSWpUfc0mqJhXGbznE6QysarOH6FBpGYYvGEaBVdNXeQHszzYhssIGu/LEntaEAviF3Ky5cDjv56jIvehuPE1S5hTO6aZHUpplHHBzYr1wuwOvCH3atrmS0U8VSALVfyv663eJ+JhnjF0z9L8re04UR4KrTyAZAHIgT/Q67onSWKdehSip9D50bCrwKtN3VkHOWgcUw2KMuzWIWgN1Iw56L3WxkM7AgIivKW1UxwHHpvi3L9XssdGSqqXmaob5KRa0wy3BYCNhrxSU6+1l9EU8xsbEfB7vP/WgCabrDOGw7MYUcONwZuLfu0RrbEYi/TqzCYiabs9eed6+xhkqosnopaBSSzxbIQ9Bu+5X02SeQYnwssjQWKHfUg0WRI05NrK4mq6iEHg0XkFJeucHiQIxIv9NEdg23lfP/+wBuvyrTFRad/qr1HWzcmINBy4="
  # NPM_API_KEY
  - secure: "ywBJgLFaSilBP6DzUKZ7o/O6oloNlDs4o89zKQN0COWQUUKiAkq3hWpmWIR37Dnu+UTBPlURaKVDSV0t9P0dcuBTMC3iApIFYKmrYTUzzuLwCCcKVGdvIlPqm8C+XzG9LTGEcQu75hk81lrqdz9lCzntPy41+AIV2aYdTJF+/JINkOI3XbUe6UCXYJZ92tP4TTG9KjzSHXoMgckYADjWWqmEwU5ojRcbsKKCMvbQtDlJ2QG6q6OM5yb+STo3tSt0E4C6tdKtiFiH4FLhaW54Qp3WqH5ctj/iiEBLBYbjqalA42dvUEOPtTMsc4jfc7MHItd/f1+Z/hJ4XdHQWO7JzXJsPbR5jtCI5B+gKweKGFyTzr7TyvEUYwc8UA99DRdfmBGZvrT6MBM/sJOF4PwpipL3DnO3JOIzcOi9EywCXiaXOOzw2XvAr1p4llaFCRSjIEAmOzIGZL0FFRczJFb6etIHkWu8xswJ7jGr+rp3aXJzb7qirqBpoKq0c5zyEMWhKHq/jp04oCLS5q/eCanXDC3IF9tvxVAU7sdt79NQp4vb7/o1Es9Q05F0MnIQFuaFC1ZowGGZjCkop93QSvQT+LOpzUKuFRnBbmBPukd5U6Ipe8OAdkjENOJ3FKKS7CRqRQ2A/eKeKRzN6QZxCsJdcN/dHp9rAaopcH1zdlfyiOk="
